### ISSUE TITLE
Create info controller

### ISSUE THREAD

**Issue by sheldonlynn** [4711Accessorize/BentoBox#16]

**Comment by sheldonlynn** [comment]
In addition to the two usecases above, you need an "info" controller. This is to be a "RESTish" service controller, returning your model data in JSON format, on demand.

This is super useful for testing.

It will need four methods:

- index() should return a description of your scenario, eg. {"scenario":"Duckey player"}
- category($key) should return the designated category, or all of them if none is specifically requested
- catalog($key) should return the designated accessory, or all of them if none is specifically requested
- bundle($key) should return the designated category, or all of them if none is specifically requested

**Comment by FrigorificInk** [comment]
What "two usescases above"?

**Comment by sheldonlynn** [comment]
@Ink-WeiZhang home page and catalog page

**Comment by sheldonlynn** [comment]
i'll take this
